# Change these first
owner: andrelug # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Iglu Online
    url: https://igluonline.com
  - name: André Lug
    url: https://andrelug.com
  - name: Above Marketing
    url: https://abovemarketing.com.br
  - name: Aeroengenharia
    url: https://aeroengenharia.com
  - name: AG Santos Engenharia
    url: http://agsantosengenharia.com.br
  - name: Alliance BH
    url: https://alliancebh.com.br
  - name: Blog Comparar
    url: https://blog.compararsegurodeviagem.com.br

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.igluonline.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://igluonline.com/wp-content/uploads/2018/12/nova-marca-branca.png
  name: Uptime Iglu
  introTitle: "Sistema para conferência do status dos sites da Iglu"
  introMessage: 
  navbar:
    - title: Iglu
      href: https://igluonline.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
